module.exports = {
	env: {
		es6: true,
		node: true
	},
	rules: {
		'block-spacing': 'error',
		'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
		'camelcase': 'error',
		'capitalized-comments': ['error', 'always', {'ignoreInlineComments': true, 'ignoreConsecutiveComments': true}],
		'comma-dangle': ['error', {'arrays': 'never', 'objects': 'never', 'imports': 'never', 'exports': 'never', 'functions': 'never'}],
		'comma-spacing': 'error',
		'comma-style': 'error',
		'eol-last': 'error',
		'consistent-this': ['error', 'self'],
		'func-call-spacing': ['error', 'never'],
		'function-paren-newline': ['error', 'never'],
		'function-call-argument-newline': ['error', 'consistent'],
		'indent': ['error', 'tab', {'SwitchCase': 1, 'VariableDeclarator': 'first', 'ArrayExpression': 1, 'ObjectExpression': 1, 'ignoreComments': true}],
		'key-spacing': ['error', {'beforeColon': false, 'afterColon': true, 'mode': 'strict'}],
		'keyword-spacing': ['error', {'before': true, 'after': true}],
		'lines-between-class-members': ['error', 'always'],
		'new-cap': ['error', {'newIsCap': true}],
		'new-parens': 'error',
		'no-lonely-if': 'error',
		'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		'object-curly-newline': ['error', {'multiline': true}],
		'spaced-comment': ['error', 'always', {'line': {'exceptions': ['-'] } }],
		'object-curly-spacing': ['error', 'never', {'objectsInObjects': true, 'arraysInObjects': true}],
		'quotes': ['error', 'single', {'avoidEscape': true, 'allowTemplateLiterals': true}],
		'no-unreachable': 'error',
		'semi': ['error', 'always'],
		'semi-style': 'error',
		'space-in-parens': 'error',
		'space-before-function-paren': ['error', 'never'],
		'arrow-spacing': 'error',
		'no-confusing-arrow': ['error', {'allowParens': false}],
		'no-const-assign': 'error',
		'no-class-assign': 'error',
		'no-dupe-class-members': 'error',
		'no-useless-constructor': 'error',
		'no-var': 'error',
		'prefer-const': 'error',
		'prefer-arrow-callback': 'error',
		'prefer-template': 'error',
		'no-undefined': 'error',
		'no-shadow': 'error',
		'no-unused-vars': 'error',
		'no-use-before-define': ['error', {'functions': false}],
		'no-undef': 'error',
		'yoda': 'error',
		'require-await': 'error',
		'no-unused-labels': 'error',
		'no-multi-spaces': 'error',
		'no-fallthrough': ['error', {'commentPattern': 'falls?\\s?through'}],
		'default-case': 'error',
		'default-case-last': 'error',
		'no-else-return': 'error',
		'eqeqeq': 'error',
		'dot-notation': ['error', {'allowPattern': '^[a-z]+(_[a-z]+)+$'}],
		'curly': ['error', 'multi-or-nest', 'consistent']
	}
};
